import "reflect-metadata";
import express from "express";
import cors from "cors";
import helmet from "helmet";
import swaggerUi from "swagger-ui-express";
import path from "node:path";
import fs from "node:fs";
import { requestLogger } from "./middleware/requestLogger";
import { errorHandler } from "./middleware/errorHandler";
import { notFound } from "./middleware/notFound";
import type { Express } from "express";
import logger from "./logger";

// NOTE: RegisterRoutes is generated by TSOA (bun run gen)
import { RegisterRoutes } from "./routes";

export function createApp(): Express {
  const app = express();

  app.use(helmet());
  app.use(cors());
  app.use(express.json({ limit: "1mb" }));

  app.use(requestLogger);

  // TSOA-generated routes (includes basePath from tsoa.json)
  RegisterRoutes(app);

  // Health check
  app.get("/healthz", (_req: express.Request, res: express.Response) =>
    res.status(200).json({ status: "ok" })
  );

  // Swagger UI and spec
  const swaggerPath = path.join(process.cwd(), "src", "swagger.json");
  const swaggerServe = swaggerUi.serve as unknown as express.RequestHandler[];
  const swaggerSetup = swaggerUi.setup(undefined, { swaggerUrl: "/swagger.json" }) as unknown as express.RequestHandler;
  app.use("/docs", ...swaggerServe, swaggerSetup);

  app.get("/swagger.json", (_req, res) => {
    try {
      if (!fs.existsSync(swaggerPath)) {
        return res.status(404).json({ message: "Swagger not generated" });
      }
      res.sendFile(swaggerPath);
    } catch (e) {
      logger.warn({ err: e }, "Failed to serve swagger.json");
      return res.status(500).json({ message: "Failed to read swagger.json" });
    }
  });

  // 404 + error handler
  app.use(notFound);
  app.use(errorHandler);

  logger.info("Application middlewares and routes registered");
  return app;
}
